### PR TITLE
Use built-in base64 URL-safe buffer encoding

### PR DESCRIPTION
**Pull request by fredrikhr**
When decoding access tokens we should use the built-in encoding `base64url` instead of trying to do our own base64-URL-safe decoding.

The existing code throws `URIError: URI malformed` for perfectly valid access tokens issued by Microsoft IDP. The proposed change now decodes these access tokens without error.

### CODE REVIEW

**Comment by AnWeber** [comment]
You won't believe how good the timing was. I just looked at https://www.npmjs.com/package/base64url.  I'll have a look and see what else is built in

**Comment by AnWeber** [comment]
The previous parsing is used by keycloak. But I look at your optimized logic: https://github.com/keycloak/keycloak/blob/main/adapters/oidc/js/src/main/resources/keycloak.js#L1048-L1065

**Comment by AnWeber** [comment]
Unfortunately, the pull request doesn't quite work. On the command line the parsing works (Node v16.1). But unfortunately not in VSCode (v14.16).

```
TypeError [ERR_UNKNOWN_ENCODING]: Unknown encoding: base64url
```
Test (Token is from jwt.io)
```
{{
const httpyac = require('httpyac');
console.info(httpyac.utils.decodeJWT('eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c'));
}}
GET https://httpbin.org/json
```

**Comment by AnWeber** [comment]
I have tested the previous code with the example token from [Micorosoft](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code#successful-authentication-response). There the parsing works.

**Comment by fredrikhr** [comment]
Hmm..., okay what about just removing the encode then decode calls? That normally really shouldn't be necessary, right?

**Comment by AnWeber** [comment]
maybe not. I look at [jose lib](https://www.npmjs.com/package/jose) how they implement the decode.
https://github.com/panva/jose/blob/bfefb4dd34a0d32e35e067a669cadcbd4aaec023/src/jwe/flattened/decrypt.ts#L195-L197
https://github.com/panva/jose/blob/bfefb4dd34a0d32e35e067a669cadcbd4aaec023/src/runtime/node/base64url.ts#L14-L19

**Comment by AnWeber** [comment]
Now I have the right path. In this case an [UnsecuredJWT](https://github.com/panva/jose/blob/6de381213d552e798d9dfa007d4bd08918b0320e/src/jwt/unsecured.ts#L89) is parsed. This uses the [`jwt_claims_set.ts` to parse the payload](https://github.com/panva/jose/blob/bfefb4dd34a0d32e35e067a669cadcbd4aaec023/src/lib/jwt_claims_set.ts#L45). This uses the [TextDecoder](https://nodejs.org/api/util.html#class-utiltextdecoder) together with the [base64.decode](https://github.com/panva/jose/blob/bfefb4dd34a0d32e35e067a669cadcbd4aaec023/src/runtime/node/base64url.ts#L14-L19)

Here's what you'd probably have to do.
```
const payload = (new TextDecoder()).decode(Buffer.from(payload, 'base64'));
```

**Comment by AnWeber** [comment]
@fredrikhr Is the change working for you? Then I would merge it like this.

**Comment by AnWeber** [comment]
I have now merged it once with TextDecoder. If it doesn't work for you, I would fix it tomorrow with a bugfix. 

Thanks for the pull request. Really nice of you to spend time for my project.

**Comment by fredrikhr** [comment]
@AnWeber yup, that worked just fine! 👍

**Pull request merged**
