### PR TITLE
Add maskedInput parameter for showInputPrompt

### LINKED ISSUE #139: Feature Request: Add `showPasswordPrompt` function to userInteractionProvider
The `UserInteractonProvider` type declares the function `showInputPrompt` function.

In order to make extensions that use different authentication flows, or for scenarios where a before-request script supplies the password or client secret for OAuth instead of reading from dotenv, it would be useful to have a function on `userInteractionProvider` that will prompt the user for input (similar to the existing `showInputPrompt` function), but which masks the input.

In VS Code the input prompt should do whatever VS Codes to mask input (e.g. when asking for SSH password). In CLI I suggest intercepting console input and either echoing back an asterisk `*` or supressing echoing completely (I personally prefer asterisk-echo).

Alternatively we could also simpli add another optional parameter `maskUserInput ?: boolean = false` to the `showInputPrompt` function.

### PR DESCRIPTION
**Pull request by fredrikhr**
fixes #139

### CODE REVIEW

**Comment by AnWeber** [comment]
You would still have to extend the parsing so that you can use it directly in http file like `{{$password input app? $value: foo}}` ([see](https://github.com/AnWeber/httpyac/blob/main/src/variables/replacer/showInputBoxVariableReplacer.ts#L17). In addition, the adaptation of the VSCode extension is missing, but I can do that too.

**Comment by fredrikhr** [comment]
VS Code: https://github.com/AnWeber/vscode-httpyac/pull/89

**Comment by AnWeber** [comment]
maybe add this code ein showInputVariableProvider

```ts
    const matchInput = /^\$(?<type>(input|password))\s*(?<placeholder>[^$]*)(\$value:\s*(?<value>.*))?\s*$/u.exec(variable);
    if (matchInput?.groups?.placeholder) {
      const placeholder = matchInput.groups.placeholder;

      const answer = await userInteractionProvider.showInputPrompt(
        placeholder,
        lastValue[placeholder] || matchInput.groups.value,
        matchInput.groups.type === 'password'
      );
```

**Comment by fredrikhr** [comment]
@AnWeber happy with https://github.com/AnWeber/httpyac/pull/140/commits/6fa9acff9740d5c4868788af305cf800ab0c534c?

**Comment by AnWeber** [comment]
Does the VSCode extension have problems with `false`, or why do you currently insist on the `undefined` call?

**Comment by fredrikhr** [comment]
I'm unsure what you mean? Would you like me to specifically provide `false` in the `else`-block here:

https://github.com/AnWeber/httpyac/blob/6fa9acff9740d5c4868788af305cf800ab0c534c/src/variables/replacer/showInputBoxVariableReplacer.ts#L23-L35

**Comment by AnWeber** [comment]
One would not have needed the `if` statement, but could directly hand over the `condition`. It just surprised me.

**Comment by fredrikhr** [comment]
Ah, I see... Yeah, I can do that 😀

**Comment by fredrikhr** [comment]
Also makes the PR-diff that much nicer 😀

**Comment by AnWeber** [comment]
yes true.

**Comment by fredrikhr** [comment]
@AnWeber I had my suspicions that you were German, but the `und` in the docs headline [Input, Password **und** QuickPick](https://httpyac.github.io/guide/variables.html#input-password-und-quickpick) was probably not meant to be there 😀 

*PS: Greetings from Norway, but I grew up and used to live in Aachen :)*

**Comment by AnWeber** [comment]
Thanks for the hint. And yes, I am German from the Bavarian Forest. Beautiful area with lots of mountains. 😀

**Pull request merged**
