### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by staff0rd**

### CODE REVIEW

**Comment by AnWeber** [comment]
🤣 How many times was it now that I typed the word wrong? I build myself a linter for this. Thanks 👍🏻

**Comment by AnWeber** [comment]
Does the command work for your use case?

**Comment by staff0rd** [comment]
My usecase was in nodejs so I prefer to use the api - i found calling `replacer.getOAuth2Response` slightly better than the last snippet I posted. I elaborated on it in [this blog post](https://staffordwilliams.com/blog/2021/12/07/better-request-management-with-httpyac/).

I think `httpyac --flow implicit -e test` is not picking up env variables - i am writing a test that proves this.

**Comment by AnWeber** [comment]
I have tested it with `.env` variables. But I was in the same folder as the variables, maybe there is the error.

**Comment by AnWeber** [comment]
I get tutoring now:-)
image

**Comment by staff0rd** [comment]
nice, i use the same!

**Pull request merged**
