### PR TITLE
Include dotenv files above the httpFile directory

### PR DESCRIPTION
**Pull request by fredrikhr**
The dotenv variable/environment provider reads dotenv-variables from the directory the httpFile is located in. However, dotenv files between the rootDirectory of the project and the httpFile directory are not taken into account.

This PR propses to walk the directories between the httpFile directory and the root directory. This allows for hierarchical dotenv variables. i.e. the one directory can define `secret_prefix`, and the sub directory can define `secret = {{secret_prefix}}-suffix`. This very helpful when you have multiple similar scenarios that require different configuration, but which still should inherit project defaults. The found dotenv-files are added in reverse order while walking the directory hierarchy from bottom to top, i.e. higher-level directory variables are overridden by lower-level directory variables.

The directory walking algortithm has several bail-outs:
- If the previous directory (starts at http file directory) joined with `..` results in a falsy value, bail
- If the previous directory joined with `..` somehow resolves to the same path, bail
  this might happen at the file-system root as `join('/', '..')` results in `'/'`
- If the previous directory joined with `..` resolves to the context root directory, bail
- If iterated through 50 directories, without reaching any of the other conditions, bail

Example:

```
context-root/
- .env:
    test_at_root = 10
- lvl1/
  - .env:
      test_lvl1 = 24
  - lvl2/
    - .env:
        test_leaf = 57
    - http-file-dir/
      - .env:
          test_leaf = 42
      - http-file.http
```

While executing requests in `context-root/lvl1/lvl2/http-file-dir/http-file.http` the dotenv-provided variables are expected to be:

```
test_at_root = 10
test_lvl1 = 24
test_leaf = 42 (Note the .env file in the http-file-dir has overwritten the value from the lvl2-dir)
```

If the http file was placed one directory higher (i.e. inside `lvl2`), `test_leaf` would be expected to have the value `57`.

**FIX**: The environments provided by dotenv-files in the httpFile directory are also taken into account when `context.config.envDir` is not defined or falsy. *Assuming the original lines 26-28 were erroneously placed within the if-block.*

### CODE REVIEW

**Comment by AnWeber** [comment]
That the build fails is a zIrcular reference. I want to fix those first and then look at PR.

**Comment by AnWeber** [comment]
What do you mean by `rootDirectory of the project`. I currently define this folder as the first folder that contains one of these files: https://github.com/AnWeber/httpyac/blob/1176178e1bf072cc167d379dfdf83bc6e8fe68e5/src/store/httpFileStore.ts#L125-L127
In this case, however, the logic makes no sense. Is for you the root folder the place where the package.json is located. Unfortunately not every project has a package.json.

**Comment by fredrikhr** [comment]
Whatever the value of `httpFile.rootDir` is.

**Comment by AnWeber** [comment]
My mistake. I have confused env directory with .env.

**Comment by AnWeber** [comment]
I am merging the feature and will add my comments afterwards. Thanks.

**Pull request merged**
