### PR TITLE
Allow async/await syntax in code snippets

### PR DESCRIPTION
**Pull request by nimatrueway**
pretty useful to be able to run asynchronous functions and collect data to pass to a request

### CODE REVIEW

**Comment by AnWeber** [comment]
I have small problems with this change. Just so we are on the same level. Async Script is already possible now. You just have to make sure that a Promise is exported (see https://httpyac.github.io/guide/scripting.html#async-await-or-promise).
```
{{
  async function wait(){
    const date = new Date();
    await sleep(10000);
    const afterDate = new Date();
    return afterDate.getTime() - date.getTime();
  }
  exports.wait = wait();
}}
GET https://httpbin.org/anything?delay={{wait}}
```

The script emulates/ is actually a CommonJS script where top level await is actually not supported (nodejs/node#21267). Several arguments against top level await do not apply here, but nevertheless I had decided against this implentation so far.

**Comment by AnWeber** [comment]
I have now finally decided against it. This PR would make it difficult for me to support ESM scripts in the future. Sorry, but I find there is an acceptable workaround.

**Comment by nimatrueway** [comment]
> I have now finally decided against it. This PR would make it difficult for me to support ESM scripts in the future. Sorry, but I find there is an acceptable workaround.

Fair enough, thanks for looking into PR Andres.

Top level await is supported by nodejs and the latest version of most browsers, in general it would be nice to have that here too.
https://stackoverflow.com/questions/46515764/how-can-i-use-async-await-at-the-top-level

**Comment by AnWeber** [comment]
I let myself be convinced. More people have already asked for this feature and if it really does cause problems, it's a breaking change. Thanks for the improvement, let's see where it goes.

**Pull request merged**
