### PR TITLE
Add PKCE option to authorization code flow

### PR DESCRIPTION
**Pull request by thzink**
Solves #219 

Remaining tasks:
- [x] Remove dependency to pkce-challenge
- [x] Unit test - at least for stringUtils.ts

### CODE REVIEW

**Comment by AnWeber** [comment]
You're welcome to try your hand at unittest, but it gets hard because of the server component. I don't have an example for it yet.

**Comment by AnWeber** [comment]
Thanks for the pull request. I will merge it and then test it manually with the keycloak. Let's see how I have to set this up.

**Comment by AnWeber** [comment]
I have adjusted one little thing. Instead of `base64Url` I use `base64`. Currently I still support NodeJS v12 and therefore I can't use this option yet. Otherwise, I have successfully tested it with Keycloak. Thank you.

**Comment by thzink** [comment]
RFC 7636, section 4.2 states that the code challenge must be base64url encoded. I assume the reason is because the code challenge is added as query parameter to the auth url. The regular base64 encoding produces characters like `+`, `/` or `=`, which have a special meaning in URLs. The base64url encoding avoids this by replacing reserved characters with unreserved ones, e.g `+` with `-` and  `/` with `_`.

When we go back to base64 we should post process the encoded string by replacing the reserved characters.

**Comment by AnWeber** [comment]
I did copy the replace from pkce_challenge and test it afterwards with Keycloak and PKCE support enabled. 

https://github.com/AnWeber/httpyac/blob/main/src/plugins/oauth2/flow/authorizationCodeFlow.ts#L124-L127

**Comment by thzink** [comment]
Just saw the code. You already took care of it. Nevermind ;-)

**Pull request merged**
